### ISSUE TITLE
"iteration_tolerance"

### ISSUE THREAD

**Issue by rjplevin** [msmasnadi/OPGEEv4#48]
There's an attribute of the `Model` class called `"iteration_tolerance"` that is used only in the file `processes/gas_partition.py`. It's defined in attributes.xml as ` <AttrDef name="iteration_tolerance" type="float">0.000001</AttrDef>`

This would be better redefined as an attribute of `GasPartition`, though it's not clear that this needs to be an attribute at all. It might be ok to define it as a constant in the `GasPartition` class, unless it's believed that users might want/need to adjust this.

@wennanlong @mbarlow12

**Comment by wennanlong** [comment]
I think the iteration_tolerance attribute doesn’t need to be a variable, especially since it's only used within processes/gas_partition.py. Agreed to make the change.
