### ISSUE TITLE
electricity in Streams

### ISSUE THREAD

**Issue by rjplevin** [msmasnadi/OPGEEv4#49]
The `Stream` class has an electricity element whose main get/set methods are used only in test files. I think it's an early implementation artifact that was never needed. Just checking with Wennan that this is the case.

Are there any cases of a `Process` passing electricity in a `Stream` to another `Process`?

**Comment by wennanlong** [comment]
You’re correct—the Stream class was designed to carry elements such as water, oil, and gas, similar to real-world scenarios. There aren’t any instances where a Process passes electricity in a Stream to another Process. It seems that the electricity attribute was an early implementation artifact, and there isn’t a need for it in our current context.

**Comment by rjplevin** [comment]
Implemented and issued PR
