### ISSUE TITLE
Missing emissions from Gas Transmission processes

### ISSUE THREAD

**Issue by lloyd-rmi** [msmasnadi/OPGEEv4#6]
We would like to calculate the emissions that would be generated during transmission of Gas and have this contribution represented in the ‘Gases’ total output.

**Comment by wennanlong** [comment]
I’ll put a placeholder on this issue for now. This request involves adding new functionality to OPGEE, so I’ll work on it after we’ve had further discussions and obtained the necessary permissions.

**Comment by wennanlong** [comment]
This feature has been added to the gas_transmission branch
